[package]
name = "yaml_sorter_rust"
version = "0.1.1"
edition = "2021"
authors = [
    "dvrkn"
]

[[bin]]
name = "ysr"
path = "src/main.rs"

[dependencies]
yaml-rust2 = "0.8.1"
clap = { version = "4.5.18", features = ["derive"] }
