# Arrays sort key
sortKey: name

preOrder:
  - global
  - enabled
  - fullImageOverride
  - apiVersion
  - kind
  - metadata
  - name
  - namespace
  - labels
  - annotations
  - goTemplate
  - generators
  - spec
  - containers
  - image
  - ports
  - protocol
  - resources
  - limits
  - requests
  - cpu
  - memory
  - volumeMount
  - destination
  - sources