on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cargo test
        run: cargo test
      - name: Release Build
        run: cargo build --release
      - name: Check artifact weight
        run: ls -lh target/release/
      - name: Before
        run: cat test.yaml
      - name: Run
        run: cargo run --release -- e test.yaml
